/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.assettrending.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetTrendingEntry service. Represents a row in the &quot;AssetTrendingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.assettrending.model.impl.AssetTrendingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.assettrending.model.impl.AssetTrendingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetTrendingEntry
 * @see com.liferay.assettrending.model.impl.AssetTrendingEntryImpl
 * @see com.liferay.assettrending.model.impl.AssetTrendingEntryModelImpl
 * @generated
 */
@ProviderType
public interface AssetTrendingEntryModel extends AttachedModel,
	BaseModel<AssetTrendingEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset trending entry model instance should use the {@link AssetTrendingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this asset trending entry.
	 *
	 * @return the primary key of this asset trending entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset trending entry.
	 *
	 * @param primaryKey the primary key of this asset trending entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset trending entry ID of this asset trending entry.
	 *
	 * @return the asset trending entry ID of this asset trending entry
	 */
	public long getAssetTrendingEntryId();

	/**
	 * Sets the asset trending entry ID of this asset trending entry.
	 *
	 * @param assetTrendingEntryId the asset trending entry ID of this asset trending entry
	 */
	public void setAssetTrendingEntryId(long assetTrendingEntryId);

	/**
	 * Returns the group ID of this asset trending entry.
	 *
	 * @return the group ID of this asset trending entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset trending entry.
	 *
	 * @param groupId the group ID of this asset trending entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset trending entry.
	 *
	 * @return the company ID of this asset trending entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset trending entry.
	 *
	 * @param companyId the company ID of this asset trending entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this asset trending entry.
	 *
	 * @return the create date of this asset trending entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset trending entry.
	 *
	 * @param createDate the create date of this asset trending entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset trending entry.
	 *
	 * @return the modified date of this asset trending entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset trending entry.
	 *
	 * @param modifiedDate the modified date of this asset trending entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset entry ID of this asset trending entry.
	 *
	 * @return the asset entry ID of this asset trending entry
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset trending entry.
	 *
	 * @param assetEntryId the asset entry ID of this asset trending entry
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the fully qualified class name of this asset trending entry.
	 *
	 * @return the fully qualified class name of this asset trending entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset trending entry.
	 *
	 * @return the class name ID of this asset trending entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset trending entry.
	 *
	 * @param classNameId the class name ID of this asset trending entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset trending entry.
	 *
	 * @return the class p k of this asset trending entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this asset trending entry.
	 *
	 * @param classPK the class p k of this asset trending entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the comment count of this asset trending entry.
	 *
	 * @return the comment count of this asset trending entry
	 */
	public int getCommentCount();

	/**
	 * Sets the comment count of this asset trending entry.
	 *
	 * @param commentCount the comment count of this asset trending entry
	 */
	public void setCommentCount(int commentCount);

	/**
	 * Returns the payload of this asset trending entry.
	 *
	 * @return the payload of this asset trending entry
	 */
	@AutoEscape
	public String getPayload();

	/**
	 * Sets the payload of this asset trending entry.
	 *
	 * @param payload the payload of this asset trending entry
	 */
	public void setPayload(String payload);

	/**
	 * Returns the priority of this asset trending entry.
	 *
	 * @return the priority of this asset trending entry
	 */
	public double getPriority();

	/**
	 * Sets the priority of this asset trending entry.
	 *
	 * @param priority the priority of this asset trending entry
	 */
	public void setPriority(double priority);

	/**
	 * Returns the rating score of this asset trending entry.
	 *
	 * @return the rating score of this asset trending entry
	 */
	public double getRatingScore();

	/**
	 * Sets the rating score of this asset trending entry.
	 *
	 * @param ratingScore the rating score of this asset trending entry
	 */
	public void setRatingScore(double ratingScore);

	/**
	 * Returns the trending score of this asset trending entry.
	 *
	 * @return the trending score of this asset trending entry
	 */
	public double getTrendingScore();

	/**
	 * Sets the trending score of this asset trending entry.
	 *
	 * @param trendingScore the trending score of this asset trending entry
	 */
	public void setTrendingScore(double trendingScore);

	/**
	 * Returns the view count of this asset trending entry.
	 *
	 * @return the view count of this asset trending entry
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this asset trending entry.
	 *
	 * @param viewCount the view count of this asset trending entry
	 */
	public void setViewCount(int viewCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetTrendingEntry assetTrendingEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetTrendingEntry> toCacheModel();

	@Override
	public AssetTrendingEntry toEscapedModel();

	@Override
	public AssetTrendingEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}